name: amr_pipeline_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - plasmidfinder
  - ncbi-amrfinderplus
  - flye
  - seqtk
  - dorado
  - fastani
  - fastqc
  - filtlong
  - samtools